services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: todo-db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
