const text = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae lacus interdum, bibendum nulla ac, egestas erat. Donec quis elementum quam. Aliquam ut nisi quis ante pharetra commodo. Fusce at odio cursus, elementum dolor nec, suscipit mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean sed ex quis dui mollis consequat. Sed commodo sem in lobortis feugiat. Pellentesque ut rutrum augue. Mauris faucibus dictum interdum. Nullam et ipsum sit amet lacus porta eleifend. Vivamus et quam placerat, blandit erat in, rutrum sapien. Maecenas diam magna, tempor ut odio et, sagittis viverra dui.

Mauris eget augue sit amet erat dignissim dictum et id elit. Ut eu elit vel metus eleifend volutpat. Mauris sit amet tristique sem, in tristique nisl. Cras tempor leo diam, faucibus ornare velit ultrices quis. In suscipit fermentum ipsum, nec pharetra libero tempus eu. Donec eget ante porta magna aliquam convallis vitae et sem. Proin et ex aliquam, lobortis mi sit amet, efficitur mauris. Vestibulum pellentesque purus in mi facilisis, eget pulvinar ligula blandit. Etiam venenatis tortor dolor, id semper justo finibus quis. Pellentesque in euismod augue, sed vehicula turpis. Sed malesuada venenatis massa, quis auctor mi accumsan et. Curabitur vel magna felis. Morbi feugiat rutrum urna, vel tempor nisi commodo nec.

In hac habitasse platea dictumst. Mauris ultricies urna ex, eget bibendum neque euismod at. Praesent nisi justo, venenatis id porta a, eleifend malesuada felis. Curabitur molestie turpis et mi luctus dictum. Curabitur ut lectus eget odio facilisis sagittis. Nunc sodales, urna sed tempus convallis, odio metus placerat dolor, non congue sem ipsum eget odio. Donec accumsan sem vel suscipit aliquet. Praesent ac purus augue. Sed purus quam, rutrum id venenatis vitae, feugiat vel nulla.

Duis sit amet nisl lobortis arcu commodo sollicitudin vel sit amet nisi. Sed cursus non nibh a cursus. Phasellus ultricies massa vel molestie placerat. Integer ultricies hendrerit sollicitudin. Sed vestibulum enim at tellus tempor mattis. Etiam eleifend vehicula sem at dapibus. Sed eu hendrerit turpis, vel gravida quam. Aliquam erat volutpat. Nunc eget arcu sed elit malesuada tristique.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam scelerisque elit eu nulla suscipit varius. Integer sit amet sapien sit amet odio fringilla tincidunt in et lectus. Vestibulum a suscipit massa. Nunc ultrices nisl eu eleifend tristique. Maecenas ante diam, euismod at arcu at, blandit sodales turpis. Mauris vel placerat mauris. Donec ornare arcu sapien, ac venenatis enim viverra eu. Vivamus semper risus vitae libero tempus iaculis. Aliquam non vestibulum urna, in interdum massa. Sed condimentum est eget varius maximus.

Phasellus fringilla porta odio, eu aliquam nisl dapibus nec. Sed dignissim dolor tempus feugiat auctor. Integer mollis, nunc nec fringilla faucibus, mauris diam dapibus metus, vel placerat ipsum nunc ac sapien. Integer tincidunt consequat placerat. Vivamus malesuada tortor quis consectetur imperdiet. Morbi rhoncus, tortor ultrices gravida ullamcorper, sapien risus egestas lectus, id sollicitudin mauris lorem sed leo. Donec quis elit nulla.

Nunc feugiat arcu facilisis, scelerisque nisl nec, vehicula nunc. Morbi porttitor bibendum dui ut placerat. Integer id porta odio. Morbi viverra nibh ut elit porttitor blandit. Ut posuere bibendum nisi at pretium. Ut congue quam at quam suscipit luctus. Ut consequat varius urna, id tincidunt massa ornare vitae.

Suspendisse nec metus quis nibh efficitur varius. Ut varius, est et dictum viverra, odio velit congue ex, quis fermentum nisi tortor et nibh. Ut id sem quis urna ultrices gravida nec nec felis. Aliquam nec feugiat nulla. Integer commodo augue in suscipit vulputate. Vivamus diam odio, ultrices lobortis sapien semper, cursus porttitor dolor. Maecenas pharetra sem ante, ut eleifend tellus tempus quis. Vestibulum sit amet accumsan ipsum, nec congue sapien. Donec auctor finibus faucibus. Fusce at est dignissim, pulvinar mi id, euismod ipsum. Donec urna mauris, interdum ac felis at, scelerisque venenatis urna. Nunc tincidunt et ex sed scelerisque. Praesent id viverra enim, at scelerisque sem. Suspendisse lobortis erat sapien, id tincidunt magna pulvinar sed. Morbi nec enim et nibh placerat volutpat. Aliquam mattis quam et auctor imperdiet.

Aliquam erat volutpat. Phasellus mattis velit id arcu euismod, et tincidunt augue iaculis. Duis mattis ipsum nisl, in pellentesque augue dapibus vel. Donec euismod nec magna a sodales. Suspendisse ac suscipit magna. Nullam et gravida lorem, sed suscipit magna. Cras interdum eu odio ac tincidunt. Duis eget placerat dolor, ac bibendum est. In sit amet tellus id lorem aliquam bibendum. Sed sed turpis odio. Nam consectetur augue vel luctus fermentum. Pellentesque ac leo quis massa feugiat viverra sed et arcu.

Praesent sed nisi enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed aliquet nulla turpis, quis vestibulum leo dapibus et. Curabitur mauris turpis, tempor sit amet tellus ac, commodo viverra sapien. Nullam ultrices dignissim posuere. Praesent quam libero, tempus non mollis a, consequat et tortor. Maecenas placerat, dolor eget convallis pharetra, quam lorem convallis turpis, non elementum nunc lectus in nisl. Sed ut est lorem. Quisque viverra quam a nulla aliquet consectetur. Aliquam laoreet gravida felis, finibus molestie arcu malesuada et. Vivamus pulvinar nibh sed sem commodo, porttitor eleifend dui tristique. Vivamus lectus eros, ultricies a aliquam in, vehicula vitae felis. Sed sit amet ipsum felis. In vehicula, enim ac congue feugiat, nunc libero faucibus felis, ac tincidunt lacus libero blandit leo. In at felis porttitor, imperdiet ex sed, elementum risus. Praesent consectetur erat porta odio fermentum efficitur.

Suspendisse aliquet iaculis elit, sit amet feugiat diam volutpat venenatis. Morbi tempus rutrum sapien, vitae lacinia enim accumsan luctus. Aliquam sagittis ornare augue in egestas. In imperdiet eleifend mauris, non maximus mauris molestie vel. Nam laoreet felis velit. Integer et nibh venenatis nisi facilisis accumsan sed a nisl. Duis arcu sapien, ornare et aliquam ac, accumsan nec ante. Phasellus sit amet efficitur nisi.

In a volutpat ipsum. Maecenas id sapien ut tellus fringilla pulvinar. Curabitur molestie rutrum fringilla. Suspendisse blandit nisl et quam porttitor euismod. Nam aliquam placerat neque, vitae porta felis ultricies vitae. Quisque magna dolor, pulvinar quis tellus sit amet, pellentesque viverra erat. Duis nec luctus tellus, sed consectetur sem. Maecenas vehicula sem nec luctus malesuada. Mauris sed rutrum orci, non sagittis nisl. Ut pharetra lorem lorem, eu rutrum nisl ultricies sit amet.

Aliquam fringilla ullamcorper nibh, in vehicula mi maximus facilisis. In aliquam arcu tortor. Nunc nec tincidunt nulla. Pellentesque sed turpis odio. Aliquam vulputate interdum lacus non hendrerit. Curabitur porttitor felis eu accumsan lobortis. Mauris tristique tempor metus, nec scelerisque diam fringilla ac. Etiam commodo maximus risus, a blandit ante sodales non. Pellentesque elementum magna id pulvinar pretium.

Curabitur ipsum sapien, pretium a lobortis luctus, mattis vitae mauris. Sed tincidunt dolor in ex porta lobortis. Praesent id elit vitae purus ornare efficitur. Proin auctor ipsum massa, a molestie sem consectetur at. Nam iaculis ligula eros. Integer nec elementum augue. Duis vel eros risus. Nam nunc lorem, tincidunt et condimentum ut, interdum ac leo. Duis vestibulum fringilla magna, et sodales nisl suscipit at. Fusce id ex nisi. Fusce cursus, arcu id dapibus lobortis, est risus pulvinar mi, consectetur blandit elit felis sed nibh. Cras non felis ut lectus sollicitudin elementum. Praesent interdum sem vitae ligula efficitur rhoncus. In congue laoreet sem nec feugiat.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam pulvinar diam gravida odio egestas porttitor nec in ante. Pellentesque massa quam, efficitur at diam non, rhoncus lobortis velit. Mauris massa nisl, pretium quis vulputate nec, laoreet in nisl. Praesent scelerisque turpis vel dolor pulvinar interdum. Pellentesque ac maximus justo, sed vehicula odio. Integer turpis tortor, aliquam et sem vel, consectetur lobortis tellus. Mauris suscipit viverra nibh sed pellentesque. Maecenas egestas erat quis urna consequat, sed laoreet metus iaculis. Phasellus malesuada sem imperdiet, tempus sapien quis, iaculis erat. Nulla facilisis vitae leo quis lacinia. Proin vel sapien id libero elementum blandit id sit amet dolor. Curabitur volutpat nibh id lorem rhoncus mattis sed vestibulum justo. Mauris gravida erat condimentum neque accumsan varius.

Maecenas at sapien sodales, sodales ipsum ac, dapibus arcu. Nunc sit amet nisi non dui sagittis dignissim ut ac ante. Sed sit amet enim gravida, consectetur lectus ut, imperdiet tortor. Sed sed orci elit. Pellentesque consectetur maximus vulputate. Mauris nec eros at risus molestie fermentum sed eu odio. Sed laoreet elementum erat nec pulvinar. Fusce sagittis eros nisl, quis placerat turpis auctor sit amet. Pellentesque odio mi, fringilla non lectus vel, accumsan scelerisque lectus. Quisque ac magna vitae tortor tincidunt varius. Mauris ac enim sapien.

Ut eget ligula quis sapien mattis bibendum. Quisque ullamcorper odio ut elit convallis malesuada. Nullam et placerat tellus, quis lacinia sem. Nunc commodo massa eu egestas rhoncus. Nunc elementum felis ut turpis vehicula, in maximus dolor pharetra. Donec vel aliquet massa, non congue est. Suspendisse ultricies, tortor nec ultricies venenatis, ligula velit suscipit metus, nec egestas ante ligula ac sem.

Duis lacinia augue id ultrices scelerisque. Ut sed mollis lectus. Nullam ut elit in ipsum porttitor interdum id non mauris. Duis mollis tristique nisi et volutpat. Duis gravida maximus felis, ac sodales eros. Mauris hendrerit sem vel elementum interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut bibendum justo sed vulputate condimentum. Etiam nec enim porta, sollicitudin magna eget, vehicula augue. Nulla condimentum vehicula tellus, sed consequat nibh euismod a.

Ut et odio quam. Proin gravida vestibulum mi vitae euismod. Donec aliquam eget mi in viverra. Aliquam porttitor tristique risus, nec sodales urna feugiat vel. Vivamus eget mauris eu lacus venenatis posuere at dictum arcu. Duis viverra nisl sit amet metus tincidunt pulvinar. Integer volutpat porttitor mauris, ut blandit lectus iaculis sit amet. Pellentesque vel ornare leo, a ultricies tellus. Ut id finibus leo. In eleifend dignissim sagittis. Mauris sagittis vehicula lorem, sit amet vulputate lorem rhoncus sit amet. Praesent maximus feugiat magna id mollis. Nunc bibendum arcu augue, id cursus sem imperdiet et. Cras lobortis magna id suscipit condimentum. Quisque malesuada lectus nunc, eu maximus nisi ultrices interdum. Nullam sit amet elit urna.

Morbi turpis quam, ultrices sit amet sagittis eget, ultrices at dolor. Aenean scelerisque ipsum at cursus pulvinar. Quisque a odio vitae massa pellentesque fringilla in vitae magna. Pellentesque auctor, ante ac mattis suscipit, urna elit ullamcorper justo, id ullamcorper lacus velit eget ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur elementum, nibh pretium rutrum dictum, dui lacus auctor ante, ut sollicitudin neque ipsum eu ligula. Curabitur eu maximus elit. Donec ullamcorper mi sed massa aliquet, vitae accumsan dui varius.
`;

export default text;